def atun():
    print("----------INGREDIENTES----------")
    print("1. Una lata de atún al agua")
    print("2. Una taza de arroz")
    print("3. 2 tazas de agua")
    print("4. Una zanahoria")
    print("5. Un morrón")
    print("6. Un diente de ajo")
    print("4. Un tomate")
    print("5. Una cebolla")
    print("6. Una lechuga")
    print("7. Aceite")
    print("8. Sal")
    print("9. Vinagre")
    print("10. Un Limón")
    
    print("-----------MATERIALES-----------")
    print("1. Una olla")
    print("2. Una cuchara")
    print("3. Un cuchillo")
    print("4. Un plato hondo")
    
    print("-----------PREPARACIÓN----------")
    print("1. Cortar la zanahoria, el morrón y el ajo en trozitos")
    print("2. Echar un chorrito de aceite a la olla")
    print("3. Poner a cocer a fuego medio la olla junto con el aceite")
    print("4. Agregar una taza de arroz a la olla")
    print("5. Freir el arroz junto con una cuchara hasta que esté bien dorado")
    print("6. Agregar 1 litro de agua a la olla")
    print("7. Esperar 2 minutos")
    print("8. Agregar la zanahoria, el morrón y el ajo a la olla")
    print("9. Esperar 12 minutos")
    print("10. Apagar el fuego de la olla")
    print("11. Cortar en trozos la lechuga")
    print("12. Agregar medio limón a la lechuga")
    print("13. Pelar y cortar en rodajas la cebolla")
    print("14. Agregar medio limón a la cebolla")
    print("15. Cortar el tomate en rodajas")
    print("16. Mezclar en un plato hondo la cebolla, la lechuga y el tomate")
    print("17. Agregar un chorrito de aceite, un chorrito de vinagre y una cuchara de sal a la mezcla")
    print("18. Agregar el atún a la mezcla")
    print("19. Mezclar bien los ingredientes")
    
def pollo_a_la_plancha():
    print("----------INGREDIENTES----------")
    print("1. Una pechuga de pollo")
    print("2. Una taza de arroz")
    print("3. 2 tazas de agua")
    print("4. Una zanahoria")
    print("5. Un morrón")
    print("6. Un diente de ajo")
    print("4. Un tomate")
    print("5. Una cebolla")
    print("6. Una lechuga")
    print("7. Aceite")
    print("8. Sal")
    print("9. Vinagre")
    print("10. Un Limón")
    
    print("-----------MATERIALES-----------")
    print("1. Una sartén")
    print("2. Una olla")
    print("3. Una espátula")
    print("4. Una cuchara")
    print("5. Un cuchillo")
    print("6. Un plato hondo")
    
    print("-----------PREPARACIÓN----------")
    print("1. Quitar la piel de la pechuga de pollo")
    print("2. Cortar la pechuga de pollo realizando cortes delgados y de forma horizontal")
    print("3. Echar un chorrito de aceite a la sartén")
    print("4. Poner a cocer a fuego medio la sartén junto con el aceite")
    print("5. Agregar el pollo a la sartén")
    print("6. Esperar a que los bordes del pollo estén dorados")
    print("7. Dar la vuelta al pollo")
    print("8. Esperar a que el pollo esté completamente dorado")
    print("9. Apagar el fuego de la sartén")
    print("10. Cortar la zanahoria, el morrón y el ajo en trozitos")
    print("11. Echar un chorrito de aceite a la olla")
    print("12. Poner a cocer a fuego medio la olla junto con el aceite")
    print("13. Agregar una taza de arroz a la olla")
    print("14. Freir el arroz junto con una cuchara hasta que esté bien dorado")
    print("15. Agregar 1 litro de agua a la olla")
    print("16. Esperar 2 minutos")
    print("17. Agregar la zanahoria, el morrón y el ajo a la olla")
    print("18. Esperar 12 minutos")
    print("19. Apagar el fuego de la olla")
    print("20. Cortar en trozos la lechuga")
    print("21. Agregar medio limón a la lechuga")
    print("22. Pelar y cortar en rodajas la cebolla")
    print("23. Agregar medio limón a la cebolla")
    print("24. Cortar el tomate en rodajas")
    print("25. Mezclar en un plato hondo la cebolla, la lechuga y el tomate")
    print("26. Agregar un chorrito de aceite, un chorrito de vinagre y una cuchara de sal a la mezcla")
    print("27. Mezclar bien las verduras")
    
def sopa_de_carne_de_res():
    print("----------INGREDIENTES----------")
    print("1. 2 litros de agua")
    print("2. Un kilo de carne de res")
    print("3. Una cebolla")
    print("4. 2 papa")
    print("5. 5 arvejas")
    print("6. 5 habas")
    print("7. Una zanahoria")
    print("8. Un racimo de apio")
    print("9. Un racimo de perejil")
    print("10. Un diente de ajo")
    print("11. Una taza de avena")
    print("12. Sal")
    
    print("-----------MATERIALES-----------")
    print("1. Una olla")
    print("2. Una cuchara")
    print("3. Un cuchillo")
    
    print("-----------PREPARACIÓN----------")
    print("1. Cortar la carne en trozos")
    print("2. Pelar las arvejas y la habas")
    print("3. Pelar y cortar las papas en trozos")
    print("4. Cortar en trozos la cebolla, el apio, el perejil y la zanahoria")
    print("5. Cortar el diente de ajo en cuadraditos")
    print("6. Echar 2 litros de agua a la olla")
    print("7. Poner a hervir a fuego medio el agua")
    print("8. Esperar 15 minutos")
    print("9. Agregar el pollo a la olla")
    print("10. Agregar 3 cucharas de sal a la olla")
    print("11. Esperar hasta que empiece a hervir más el agua")
    print("12. Bajar a fuego bajo la llama")
    print("13. Esperar 2 horas")
    print("14. Agregar la cebolla y el ajo a la olla")
    print("15. Esperar hasta que la cebolla y el ajo estén blandos")
    print("16. Agregar la papa y la zanahoria a la olla")
    print("17. Esperar a que la papa y la zanahoria estén blandas")
    print("18. Agregar la arveja y la haba a la olla")
    print("19. Esperar a que la arveja y la haba estén blandas")
    print("20. Agregar el apio y el perejil a la olla")
    print("21. Agregar una taza de avena a la olla")
    print("22. Esperar 15 minutos")
    
def sopa_de_pollo():
    print("----------INGREDIENTES----------")
    print("1. 2 litros de agua")
    print("2. Un pollo entero")
    print("3. Una cebolla")
    print("4. 2 papa")
    print("5. 5 arvejas")
    print("6. 5 habas")
    print("7. Una zanahoria")
    print("8. Un racimo de apio")
    print("9. Un racimo de perejil")
    print("10. Un diente de ajo")
    print("11. Una taza de avena")
    print("12. Sal")
    
    print("-----------MATERIALES-----------")
    print("1. Una olla")
    print("2. Una cuchara")
    print("3. Un cuchillo")
    
    print("-----------PREPARACIÓN----------")
    print("1. Cortar el pollo en presas")
    print("2. Pelar las arvejas y la habas")
    print("3. Pelar y cortar las papas en rodajas")
    print("4. Cortar en trozos la cebolla, el apio, el perejil y la zanahoria")
    print("5. Cortar el diente de ajo en cuadraditos")
    print("6. Echar 2 litros de agua a la olla")
    print("7. Poner a hervir a fuego medio el agua")
    print("8. Esperar 15 minutos")
    print("9. Agregar el pollo a la olla")
    print("10. Agregar 3 cucharas de sal a la olla")
    print("11. Esperar hasta que empiece a hervir más el agua")
    print("12. Bajar a fuego bajo la llama")
    print("13. Esperar 20 minutos")
    print("14. Agregar la cebolla y el ajo a la olla")
    print("15. Esperar hasta que la cebolla y el ajo estén blandos")
    print("16. Agregar la papa y la zanahoria a la olla")
    print("17. Esperar a que la papa y la zanahoria estén blandas")
    print("18. Agregar la arveja y la haba a la olla")
    print("19. Esperar a que la arveja y la haba estén blandas")
    print("20. Agregar el apio y el perejil a la olla")
    print("21. Agregar una taza de avena a la olla")
    print("22. Esperar 15 minutos")
    
def mate_de_poleo():
    print("----------INGREDIENTES----------")
    print("1. Miel")
    print("2. Hierba mate")
    print("3. 4 hojas de poleo")
    print("-----------MATERIALES-----------")
    print("1. Poro")
    print("2. Bombilla del poro")
    print("3. Termo con agua caliente")
    
    print("-----------PREPARACIÓN----------")
    print("1. Agregar una cucharadita de miel al poro")
    print("2. Agregar hierba mate hasta la mitad del poro")
    print("3. Agregar 4 hojas de poleo al poro")
    print("4. Echar agua caliente al poro hasta llenarlo")
    
def mate_de_manzanilla():
    print("----------INGREDIENTES----------")
    print("1. Miel")
    print("2. Hierba mate")
    print("3. 5 flores de manzanilla")
    
    print("-----------MATERIALES-----------")
    print("1. Poro")
    print("2. Bombilla del poro")
    print("3. Termo con agua caliente")
    
    print("-----------PREPARACIÓN----------")
    print("1. Agregar 1 cucharadita de miel al poro")
    print("2. Agregar hierba mate hasta la mitad del poro")
    print("3. Agregar 5 flores de manzanilla al poro")
    print("4. Echar agua caliente al poro hasta llenarlo")

print("Bienvenido/a al menú de almuerzos saludables")
print("Seleccione qué tipo de recetas le gustaría aprender")
print("1. Sopas")
print("2. Segundos")
print("3. Mates")
tipo_receta=input()
if tipo_receta=="1":
    print("Seleccione qué receta le gustaría aprender")
    print("1. Sopa de pollo")
    print("2. Sopa de carne de res")
    receta1=input()
    if receta1=="1":
        sopa_de_pollo()
    elif receta1=="2":
        sopa_de_carne_de_res()
    else:
        print("Carácter inválido")
elif tipo_receta=="2":
    print("Seleccione qué receta le gustaría aprender")
    print("1. Pollo a la plancha")
    print("2. Atún")
    receta2=input()
    if receta2=="1":
        pollo_a_la_plancha()
    elif receta2=="2":
        atun()
    else:
        print("Carácter inválido")
    
elif tipo_receta=="3":
    print("Seleccione qué receta le gustaría aprender")
    print("1. Mate de manzanilla")
    print("2. Mate de poleo")
    receta3=input()
    if receta3=="1":
        mate_de_manzanilla()
    elif receta3=="2":
        mate_de_poleo()
    else:
        print("Carácter inválido")
else:
    print("Carácter inválido")